// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime.ts';
import {
    IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview,
    IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewFromJSON,
    IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewToJSON,
    IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview,
    IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewFromJSON,
    IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewToJSON,
    IoK8sApiAuthorizationV1beta1SelfSubjectRulesReview,
    IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewFromJSON,
    IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewToJSON,
    IoK8sApiAuthorizationV1beta1SubjectAccessReview,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewFromJSON,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewToJSON,
    IoK8sApimachineryPkgApisMetaV1APIResourceList,
    IoK8sApimachineryPkgApisMetaV1APIResourceListFromJSON,
    IoK8sApimachineryPkgApisMetaV1APIResourceListToJSON,
} from '../models.ts';

export interface CreateAuthorizationV1beta1NamespacedLocalSubjectAccessReviewRequest {
    namespace: string;
    body: IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview;
    dryRun?: string;
    fieldManager?: string;
    pretty?: string;
}

export interface CreateAuthorizationV1beta1SelfSubjectAccessReviewRequest {
    body: IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview;
    dryRun?: string;
    fieldManager?: string;
    pretty?: string;
}

export interface CreateAuthorizationV1beta1SelfSubjectRulesReviewRequest {
    body: IoK8sApiAuthorizationV1beta1SelfSubjectRulesReview;
    dryRun?: string;
    fieldManager?: string;
    pretty?: string;
}

export interface CreateAuthorizationV1beta1SubjectAccessReviewRequest {
    body: IoK8sApiAuthorizationV1beta1SubjectAccessReview;
    dryRun?: string;
    fieldManager?: string;
    pretty?: string;
}

/**
 * no description
 */
export class AuthorizationV1beta1Api extends runtime.BaseAPI {

    /**
     * create a LocalSubjectAccessReview
     */
    async createAuthorizationV1beta1NamespacedLocalSubjectAccessReviewRaw(requestParameters: CreateAuthorizationV1beta1NamespacedLocalSubjectAccessReviewRequest): Promise<runtime.ApiResponse<IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview>> {
        if (requestParameters.namespace === null || requestParameters.namespace === undefined) {
            throw new runtime.RequiredError('namespace','Required parameter requestParameters.namespace was null or undefined when calling createAuthorizationV1beta1NamespacedLocalSubjectAccessReview.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createAuthorizationV1beta1NamespacedLocalSubjectAccessReview.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.dryRun !== undefined) {
            queryParameters['dryRun'] = requestParameters.dryRun;
        }

        if (requestParameters.fieldManager !== undefined) {
            queryParameters['fieldManager'] = requestParameters.fieldManager;
        }

        if (requestParameters.pretty !== undefined) {
            queryParameters['pretty'] = requestParameters.pretty;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // BearerToken authentication
        }

        const response = await this.request({
            path: `/apis/authorization.k8s.io/v1beta1/namespaces/{namespace}/localsubjectaccessreviews`.replace(`{${"namespace"}}`, encodeURIComponent(String(requestParameters.namespace))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewFromJSON(jsonValue));
    }

    /**
     * create a LocalSubjectAccessReview
     */
    async createAuthorizationV1beta1NamespacedLocalSubjectAccessReview(requestParameters: CreateAuthorizationV1beta1NamespacedLocalSubjectAccessReviewRequest): Promise<IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview> {
        const response = await this.createAuthorizationV1beta1NamespacedLocalSubjectAccessReviewRaw(requestParameters);
        return await response.value();
    }

    /**
     * create a SelfSubjectAccessReview
     */
    async createAuthorizationV1beta1SelfSubjectAccessReviewRaw(requestParameters: CreateAuthorizationV1beta1SelfSubjectAccessReviewRequest): Promise<runtime.ApiResponse<IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createAuthorizationV1beta1SelfSubjectAccessReview.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.dryRun !== undefined) {
            queryParameters['dryRun'] = requestParameters.dryRun;
        }

        if (requestParameters.fieldManager !== undefined) {
            queryParameters['fieldManager'] = requestParameters.fieldManager;
        }

        if (requestParameters.pretty !== undefined) {
            queryParameters['pretty'] = requestParameters.pretty;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // BearerToken authentication
        }

        const response = await this.request({
            path: `/apis/authorization.k8s.io/v1beta1/selfsubjectaccessreviews`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApiAuthorizationV1beta1SelfSubjectAccessReviewFromJSON(jsonValue));
    }

    /**
     * create a SelfSubjectAccessReview
     */
    async createAuthorizationV1beta1SelfSubjectAccessReview(requestParameters: CreateAuthorizationV1beta1SelfSubjectAccessReviewRequest): Promise<IoK8sApiAuthorizationV1beta1SelfSubjectAccessReview> {
        const response = await this.createAuthorizationV1beta1SelfSubjectAccessReviewRaw(requestParameters);
        return await response.value();
    }

    /**
     * create a SelfSubjectRulesReview
     */
    async createAuthorizationV1beta1SelfSubjectRulesReviewRaw(requestParameters: CreateAuthorizationV1beta1SelfSubjectRulesReviewRequest): Promise<runtime.ApiResponse<IoK8sApiAuthorizationV1beta1SelfSubjectRulesReview>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createAuthorizationV1beta1SelfSubjectRulesReview.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.dryRun !== undefined) {
            queryParameters['dryRun'] = requestParameters.dryRun;
        }

        if (requestParameters.fieldManager !== undefined) {
            queryParameters['fieldManager'] = requestParameters.fieldManager;
        }

        if (requestParameters.pretty !== undefined) {
            queryParameters['pretty'] = requestParameters.pretty;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // BearerToken authentication
        }

        const response = await this.request({
            path: `/apis/authorization.k8s.io/v1beta1/selfsubjectrulesreviews`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApiAuthorizationV1beta1SelfSubjectRulesReviewFromJSON(jsonValue));
    }

    /**
     * create a SelfSubjectRulesReview
     */
    async createAuthorizationV1beta1SelfSubjectRulesReview(requestParameters: CreateAuthorizationV1beta1SelfSubjectRulesReviewRequest): Promise<IoK8sApiAuthorizationV1beta1SelfSubjectRulesReview> {
        const response = await this.createAuthorizationV1beta1SelfSubjectRulesReviewRaw(requestParameters);
        return await response.value();
    }

    /**
     * create a SubjectAccessReview
     */
    async createAuthorizationV1beta1SubjectAccessReviewRaw(requestParameters: CreateAuthorizationV1beta1SubjectAccessReviewRequest): Promise<runtime.ApiResponse<IoK8sApiAuthorizationV1beta1SubjectAccessReview>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createAuthorizationV1beta1SubjectAccessReview.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.dryRun !== undefined) {
            queryParameters['dryRun'] = requestParameters.dryRun;
        }

        if (requestParameters.fieldManager !== undefined) {
            queryParameters['fieldManager'] = requestParameters.fieldManager;
        }

        if (requestParameters.pretty !== undefined) {
            queryParameters['pretty'] = requestParameters.pretty;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // BearerToken authentication
        }

        const response = await this.request({
            path: `/apis/authorization.k8s.io/v1beta1/subjectaccessreviews`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IoK8sApiAuthorizationV1beta1SubjectAccessReviewToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApiAuthorizationV1beta1SubjectAccessReviewFromJSON(jsonValue));
    }

    /**
     * create a SubjectAccessReview
     */
    async createAuthorizationV1beta1SubjectAccessReview(requestParameters: CreateAuthorizationV1beta1SubjectAccessReviewRequest): Promise<IoK8sApiAuthorizationV1beta1SubjectAccessReview> {
        const response = await this.createAuthorizationV1beta1SubjectAccessReviewRaw(requestParameters);
        return await response.value();
    }

    /**
     * get available resources
     */
    async getAuthorizationV1beta1APIResourcesRaw(): Promise<runtime.ApiResponse<IoK8sApimachineryPkgApisMetaV1APIResourceList>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["authorization"] = this.configuration.apiKey("authorization"); // BearerToken authentication
        }

        const response = await this.request({
            path: `/apis/authorization.k8s.io/v1beta1/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => IoK8sApimachineryPkgApisMetaV1APIResourceListFromJSON(jsonValue));
    }

    /**
     * get available resources
     */
    async getAuthorizationV1beta1APIResources(): Promise<IoK8sApimachineryPkgApisMetaV1APIResourceList> {
        const response = await this.getAuthorizationV1beta1APIResourcesRaw();
        return await response.value();
    }

}
