// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 * @export
 * @interface IoK8sApiCoreV1HTTPHeader
 */
export interface IoK8sApiCoreV1HTTPHeader {
    /**
     * The header field name
     * @type {string}
     * @memberof IoK8sApiCoreV1HTTPHeader
     */
    name: string;
    /**
     * The header field value
     * @type {string}
     * @memberof IoK8sApiCoreV1HTTPHeader
     */
    value: string;
}

export function IoK8sApiCoreV1HTTPHeaderFromJSON(json: any): IoK8sApiCoreV1HTTPHeader {
    return {
        'name': json['name'],
        'value': json['value'],
    };
}

export function IoK8sApiCoreV1HTTPHeaderToJSON(value?: IoK8sApiCoreV1HTTPHeader): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'value': value.value,
    };
}


