// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CustomResourceDefinitionNames indicates the names to serve this CustomResourceDefinition
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames {
    /**
     * Categories is a list of grouped resources custom resources belong to (e.g. \'all\')
     * @type {Array<string>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    categories?: Array<string>;
    /**
     * Kind is the serialized kind of the resource.  It is normally CamelCase and singular.
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    kind: string;
    /**
     * ListKind is the serialized kind of the list for this resource.  Defaults to <kind>List.
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    listKind?: string;
    /**
     * Plural is the plural name of the resource to serve.  It must match the name of the CustomResourceDefinition-registration too: plural.group and it must be all lowercase.
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    plural: string;
    /**
     * ShortNames are short names for the resource.  It must be all lowercase.
     * @type {Array<string>}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    shortNames?: Array<string>;
    /**
     * Singular is the singular name of the resource.  It must be all lowercase  Defaults to lowercased <kind>
     * @type {string}
     * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
     */
    singular?: string;
}

export function IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNamesFromJSON(json: any): IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames {
    return {
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'kind': json['kind'],
        'listKind': !exists(json, 'listKind') ? undefined : json['listKind'],
        'plural': json['plural'],
        'shortNames': !exists(json, 'shortNames') ? undefined : json['shortNames'],
        'singular': !exists(json, 'singular') ? undefined : json['singular'],
    };
}

export function IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNamesToJSON(value?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'categories': value.categories,
        'kind': value.kind,
        'listKind': value.listKind,
        'plural': value.plural,
        'shortNames': value.shortNames,
        'singular': value.singular,
    };
}


