// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * AzureFile represents an Azure File Service mount on the host and bind mount to the pod.
 * @export
 * @interface IoK8sApiCoreV1AzureFileVolumeSource
 */
export interface IoK8sApiCoreV1AzureFileVolumeSource {
    /**
     * Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
     * @type {boolean}
     * @memberof IoK8sApiCoreV1AzureFileVolumeSource
     */
    readOnly?: boolean;
    /**
     * the name of secret that contains Azure Storage Account Name and Key
     * @type {string}
     * @memberof IoK8sApiCoreV1AzureFileVolumeSource
     */
    secretName: string;
    /**
     * Share Name
     * @type {string}
     * @memberof IoK8sApiCoreV1AzureFileVolumeSource
     */
    shareName: string;
}

export function IoK8sApiCoreV1AzureFileVolumeSourceFromJSON(json: any): IoK8sApiCoreV1AzureFileVolumeSource {
    return {
        'readOnly': !exists(json, 'readOnly') ? undefined : json['readOnly'],
        'secretName': json['secretName'],
        'shareName': json['shareName'],
    };
}

export function IoK8sApiCoreV1AzureFileVolumeSourceToJSON(value?: IoK8sApiCoreV1AzureFileVolumeSource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'readOnly': value.readOnly,
        'secretName': value.secretName,
        'shareName': value.shareName,
    };
}


