// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * EndpointPort is a tuple that describes a single port.
 * @export
 * @interface IoK8sApiCoreV1EndpointPort
 */
export interface IoK8sApiCoreV1EndpointPort {
    /**
     * The name of this port (corresponds to ServicePort.Name). Must be a DNS_LABEL. Optional only if one port is defined.
     * @type {string}
     * @memberof IoK8sApiCoreV1EndpointPort
     */
    name?: string;
    /**
     * The port number of the endpoint.
     * @type {number}
     * @memberof IoK8sApiCoreV1EndpointPort
     */
    port: number;
    /**
     * The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
     * @type {string}
     * @memberof IoK8sApiCoreV1EndpointPort
     */
    protocol?: string;
}

export function IoK8sApiCoreV1EndpointPortFromJSON(json: any): IoK8sApiCoreV1EndpointPort {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'port': json['port'],
        'protocol': !exists(json, 'protocol') ? undefined : json['protocol'],
    };
}

export function IoK8sApiCoreV1EndpointPortToJSON(value?: IoK8sApiCoreV1EndpointPort): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'port': value.port,
        'protocol': value.protocol,
    };
}


