// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAppsV1beta2DaemonSetSpec,
    IoK8sApiAppsV1beta2DaemonSetSpecFromJSON,
    IoK8sApiAppsV1beta2DaemonSetSpecToJSON,
    IoK8sApiAppsV1beta2DaemonSetStatus,
    IoK8sApiAppsV1beta2DaemonSetStatusFromJSON,
    IoK8sApiAppsV1beta2DaemonSetStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * DEPRECATED - This group version of DaemonSet is deprecated by apps/v1/DaemonSet. See the release notes for more information. DaemonSet represents the configuration of a daemon set.
 * @export
 * @interface IoK8sApiAppsV1beta2DaemonSet
 */
export interface IoK8sApiAppsV1beta2DaemonSet {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2DaemonSet
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2DaemonSet
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAppsV1beta2DaemonSet
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2DaemonSetSpec}
     * @memberof IoK8sApiAppsV1beta2DaemonSet
     */
    spec?: IoK8sApiAppsV1beta2DaemonSetSpec;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2DaemonSetStatus}
     * @memberof IoK8sApiAppsV1beta2DaemonSet
     */
    status?: IoK8sApiAppsV1beta2DaemonSetStatus;
}

export function IoK8sApiAppsV1beta2DaemonSetFromJSON(json: any): IoK8sApiAppsV1beta2DaemonSet {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : IoK8sApiAppsV1beta2DaemonSetSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiAppsV1beta2DaemonSetStatusFromJSON(json['status']),
    };
}

export function IoK8sApiAppsV1beta2DaemonSetToJSON(value?: IoK8sApiAppsV1beta2DaemonSet): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiAppsV1beta2DaemonSetSpecToJSON(value.spec),
        'status': IoK8sApiAppsV1beta2DaemonSetStatusToJSON(value.status),
    };
}


