// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiExtensionsV1beta1IDRange,
    IoK8sApiExtensionsV1beta1IDRangeFromJSON,
    IoK8sApiExtensionsV1beta1IDRangeToJSON,
} from './index.ts';

/**
 * SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy. Deprecated: use SupplementalGroupsStrategyOptions from policy API Group instead.
 * @export
 * @interface IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions
 */
export interface IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions {
    /**
     * ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.
     * @type {Array<IoK8sApiExtensionsV1beta1IDRange>}
     * @memberof IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions
     */
    ranges?: Array<IoK8sApiExtensionsV1beta1IDRange>;
    /**
     * rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions
     */
    rule?: string;
}

export function IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptionsFromJSON(json: any): IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions {
    return {
        'ranges': !exists(json, 'ranges') ? undefined : (json['ranges'] as Array<any>).map(IoK8sApiExtensionsV1beta1IDRangeFromJSON),
        'rule': !exists(json, 'rule') ? undefined : json['rule'],
    };
}

export function IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptionsToJSON(value?: IoK8sApiExtensionsV1beta1SupplementalGroupsStrategyOptions): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'ranges': value.ranges === undefined ? undefined : (value.ranges as Array<any>).map(IoK8sApiExtensionsV1beta1IDRangeToJSON),
        'rule': value.rule,
    };
}


