// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiRbacV1beta1AggregationRule,
    IoK8sApiRbacV1beta1AggregationRuleFromJSON,
    IoK8sApiRbacV1beta1AggregationRuleToJSON,
    IoK8sApiRbacV1beta1PolicyRule,
    IoK8sApiRbacV1beta1PolicyRuleFromJSON,
    IoK8sApiRbacV1beta1PolicyRuleToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './';

/**
 * ClusterRole is a cluster level, logical grouping of PolicyRules that can be referenced as a unit by a RoleBinding or ClusterRoleBinding.
 * @export
 * @interface IoK8sApiRbacV1beta1ClusterRole
 */
export interface IoK8sApiRbacV1beta1ClusterRole {
    /**
     * 
     * @type {IoK8sApiRbacV1beta1AggregationRule}
     * @memberof IoK8sApiRbacV1beta1ClusterRole
     */
    aggregationRule?: IoK8sApiRbacV1beta1AggregationRule;
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiRbacV1beta1ClusterRole
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiRbacV1beta1ClusterRole
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiRbacV1beta1ClusterRole
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * Rules holds all the PolicyRules for this ClusterRole
     * @type {Array<IoK8sApiRbacV1beta1PolicyRule>}
     * @memberof IoK8sApiRbacV1beta1ClusterRole
     */
    rules?: Array<IoK8sApiRbacV1beta1PolicyRule>;
}

export function IoK8sApiRbacV1beta1ClusterRoleFromJSON(json: any): IoK8sApiRbacV1beta1ClusterRole {
    return {
        'aggregationRule': !exists(json, 'aggregationRule') ? undefined : IoK8sApiRbacV1beta1AggregationRuleFromJSON(json['aggregationRule']),
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'rules': !exists(json, 'rules') ? undefined : (json['rules'] as Array<any>).map(IoK8sApiRbacV1beta1PolicyRuleFromJSON),
    };
}

export function IoK8sApiRbacV1beta1ClusterRoleToJSON(value?: IoK8sApiRbacV1beta1ClusterRole): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'aggregationRule': IoK8sApiRbacV1beta1AggregationRuleToJSON(value.aggregationRule),
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'rules': value.rules === undefined ? undefined : (value.rules as Array<any>).map(IoK8sApiRbacV1beta1PolicyRuleToJSON),
    };
}


