// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON,
    IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON,
    IoK8sApiAutoscalingV2beta2MetricTarget,
    IoK8sApiAutoscalingV2beta2MetricTargetFromJSON,
    IoK8sApiAutoscalingV2beta2MetricTargetToJSON,
} from './index.ts';

/**
 * PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2PodsMetricSource
 */
export interface IoK8sApiAutoscalingV2beta2PodsMetricSource {
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2PodsMetricSource
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2MetricTarget}
     * @memberof IoK8sApiAutoscalingV2beta2PodsMetricSource
     */
    target: IoK8sApiAutoscalingV2beta2MetricTarget;
}

export function IoK8sApiAutoscalingV2beta2PodsMetricSourceFromJSON(json: any): IoK8sApiAutoscalingV2beta2PodsMetricSource {
    return {
        'metric': IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON(json['metric']),
        'target': IoK8sApiAutoscalingV2beta2MetricTargetFromJSON(json['target']),
    };
}

export function IoK8sApiAutoscalingV2beta2PodsMetricSourceToJSON(value?: IoK8sApiAutoscalingV2beta2PodsMetricSource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'metric': IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON(value.metric),
        'target': IoK8sApiAutoscalingV2beta2MetricTargetToJSON(value.target),
    };
}


