// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * DEPRECATED 1.9 - This group version of NetworkPolicyPort is deprecated by networking/v1/NetworkPolicyPort.
 * @export
 * @interface IoK8sApiExtensionsV1beta1NetworkPolicyPort
 */
export interface IoK8sApiExtensionsV1beta1NetworkPolicyPort {
    /**
     * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyPort
     */
    port?: string;
    /**
     * Optional.  The protocol (TCP, UDP, or SCTP) which traffic must match. If not specified, this field defaults to TCP.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyPort
     */
    protocol?: string;
}

export function IoK8sApiExtensionsV1beta1NetworkPolicyPortFromJSON(json: any): IoK8sApiExtensionsV1beta1NetworkPolicyPort {
    return {
        'port': !exists(json, 'port') ? undefined : json['port'],
        'protocol': !exists(json, 'protocol') ? undefined : json['protocol'],
    };
}

export function IoK8sApiExtensionsV1beta1NetworkPolicyPortToJSON(value?: IoK8sApiExtensionsV1beta1NetworkPolicyPort): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'port': value.port,
        'protocol': value.protocol,
    };
}


