// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * JobCondition describes current state of a job.
 * @export
 * @interface IoK8sApiBatchV1JobCondition
 */
export interface IoK8sApiBatchV1JobCondition {
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    lastProbeTime?: Date;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    lastTransitionTime?: Date;
    /**
     * Human readable message indicating details about last transition.
     * @type {string}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    message?: string;
    /**
     * (brief) reason for the condition\'s last transition.
     * @type {string}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    reason?: string;
    /**
     * Status of the condition, one of True, False, Unknown.
     * @type {string}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    status: string;
    /**
     * Type of job condition, Complete or Failed.
     * @type {string}
     * @memberof IoK8sApiBatchV1JobCondition
     */
    type: string;
}

export function IoK8sApiBatchV1JobConditionFromJSON(json: any): IoK8sApiBatchV1JobCondition {
    return {
        'lastProbeTime': !exists(json, 'lastProbeTime') ? undefined : new Date(json['lastProbeTime']),
        'lastTransitionTime': !exists(json, 'lastTransitionTime') ? undefined : new Date(json['lastTransitionTime']),
        'message': !exists(json, 'message') ? undefined : json['message'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'status': json['status'],
        'type': json['type'],
    };
}

export function IoK8sApiBatchV1JobConditionToJSON(value?: IoK8sApiBatchV1JobCondition): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'lastProbeTime': value.lastProbeTime === undefined ? undefined : value.lastProbeTime.toISOString(),
        'lastTransitionTime': value.lastTransitionTime === undefined ? undefined : value.lastTransitionTime.toISOString(),
        'message': value.message,
        'reason': value.reason,
        'status': value.status,
        'type': value.type,
    };
}


