// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * DEPRECATED.
 * @export
 * @interface IoK8sApiExtensionsV1beta1RollbackConfig
 */
export interface IoK8sApiExtensionsV1beta1RollbackConfig {
    /**
     * The revision to rollback to. If set to 0, rollback to the last revision.
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1RollbackConfig
     */
    revision?: number;
}

export function IoK8sApiExtensionsV1beta1RollbackConfigFromJSON(json: any): IoK8sApiExtensionsV1beta1RollbackConfig {
    return {
        'revision': !exists(json, 'revision') ? undefined : json['revision'],
    };
}

export function IoK8sApiExtensionsV1beta1RollbackConfigToJSON(value?: IoK8sApiExtensionsV1beta1RollbackConfig): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'revision': value.revision,
    };
}


