// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiExtensionsV1beta1ReplicaSetCondition,
    IoK8sApiExtensionsV1beta1ReplicaSetConditionFromJSON,
    IoK8sApiExtensionsV1beta1ReplicaSetConditionToJSON,
} from './';

/**
 * ReplicaSetStatus represents the current status of a ReplicaSet.
 * @export
 * @interface IoK8sApiExtensionsV1beta1ReplicaSetStatus
 */
export interface IoK8sApiExtensionsV1beta1ReplicaSetStatus {
    /**
     * The number of available replicas (ready for at least minReadySeconds) for this replica set.
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    availableReplicas?: number;
    /**
     * Represents the latest available observations of a replica set\'s current state.
     * @type {Array<IoK8sApiExtensionsV1beta1ReplicaSetCondition>}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    conditions?: Array<IoK8sApiExtensionsV1beta1ReplicaSetCondition>;
    /**
     * The number of pods that have labels matching the labels of the pod template of the replicaset.
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    fullyLabeledReplicas?: number;
    /**
     * ObservedGeneration reflects the generation of the most recently observed ReplicaSet.
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    observedGeneration?: number;
    /**
     * The number of ready replicas for this replica set.
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    readyReplicas?: number;
    /**
     * Replicas is the most recently oberved number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller
     * @type {number}
     * @memberof IoK8sApiExtensionsV1beta1ReplicaSetStatus
     */
    replicas: number;
}

export function IoK8sApiExtensionsV1beta1ReplicaSetStatusFromJSON(json: any): IoK8sApiExtensionsV1beta1ReplicaSetStatus {
    return {
        'availableReplicas': !exists(json, 'availableReplicas') ? undefined : json['availableReplicas'],
        'conditions': !exists(json, 'conditions') ? undefined : (json['conditions'] as Array<any>).map(IoK8sApiExtensionsV1beta1ReplicaSetConditionFromJSON),
        'fullyLabeledReplicas': !exists(json, 'fullyLabeledReplicas') ? undefined : json['fullyLabeledReplicas'],
        'observedGeneration': !exists(json, 'observedGeneration') ? undefined : json['observedGeneration'],
        'readyReplicas': !exists(json, 'readyReplicas') ? undefined : json['readyReplicas'],
        'replicas': json['replicas'],
    };
}

export function IoK8sApiExtensionsV1beta1ReplicaSetStatusToJSON(value?: IoK8sApiExtensionsV1beta1ReplicaSetStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'availableReplicas': value.availableReplicas,
        'conditions': value.conditions === undefined ? undefined : (value.conditions as Array<any>).map(IoK8sApiExtensionsV1beta1ReplicaSetConditionToJSON),
        'fullyLabeledReplicas': value.fullyLabeledReplicas,
        'observedGeneration': value.observedGeneration,
        'readyReplicas': value.readyReplicas,
        'replicas': value.replicas,
    };
}


