// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategy,
    IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategyFromJSON,
    IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategyToJSON,
} from './';

/**
 * StatefulSetUpdateStrategy indicates the strategy that the StatefulSet controller will use to perform updates. It includes any additional parameters necessary to perform the update for the indicated strategy.
 * @export
 * @interface IoK8sApiAppsV1beta2StatefulSetUpdateStrategy
 */
export interface IoK8sApiAppsV1beta2StatefulSetUpdateStrategy {
    /**
     * 
     * @type {IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategy}
     * @memberof IoK8sApiAppsV1beta2StatefulSetUpdateStrategy
     */
    rollingUpdate?: IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategy;
    /**
     * Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2StatefulSetUpdateStrategy
     */
    type?: string;
}

export function IoK8sApiAppsV1beta2StatefulSetUpdateStrategyFromJSON(json: any): IoK8sApiAppsV1beta2StatefulSetUpdateStrategy {
    return {
        'rollingUpdate': !exists(json, 'rollingUpdate') ? undefined : IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategyFromJSON(json['rollingUpdate']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function IoK8sApiAppsV1beta2StatefulSetUpdateStrategyToJSON(value?: IoK8sApiAppsV1beta2StatefulSetUpdateStrategy): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'rollingUpdate': IoK8sApiAppsV1beta2RollingUpdateStatefulSetStrategyToJSON(value.rollingUpdate),
        'type': value.type,
    };
}


