// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiCoreV1PodAffinityTerm,
    IoK8sApiCoreV1PodAffinityTermFromJSON,
    IoK8sApiCoreV1PodAffinityTermToJSON,
} from './index.ts';

/**
 * The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
 * @export
 * @interface IoK8sApiCoreV1WeightedPodAffinityTerm
 */
export interface IoK8sApiCoreV1WeightedPodAffinityTerm {
    /**
     * 
     * @type {IoK8sApiCoreV1PodAffinityTerm}
     * @memberof IoK8sApiCoreV1WeightedPodAffinityTerm
     */
    podAffinityTerm: IoK8sApiCoreV1PodAffinityTerm;
    /**
     * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
     * @type {number}
     * @memberof IoK8sApiCoreV1WeightedPodAffinityTerm
     */
    weight: number;
}

export function IoK8sApiCoreV1WeightedPodAffinityTermFromJSON(json: any): IoK8sApiCoreV1WeightedPodAffinityTerm {
    return {
        'podAffinityTerm': IoK8sApiCoreV1PodAffinityTermFromJSON(json['podAffinityTerm']),
        'weight': json['weight'],
    };
}

export function IoK8sApiCoreV1WeightedPodAffinityTermToJSON(value?: IoK8sApiCoreV1WeightedPodAffinityTerm): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'podAffinityTerm': IoK8sApiCoreV1PodAffinityTermToJSON(value.podAffinityTerm),
        'weight': value.weight,
    };
}


