// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * IngressBackend describes all endpoints for a given service and port.
 * @export
 * @interface IoK8sApiExtensionsV1beta1IngressBackend
 */
export interface IoK8sApiExtensionsV1beta1IngressBackend {
    /**
     * Specifies the name of the referenced service.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1IngressBackend
     */
    serviceName: string;
    /**
     * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1IngressBackend
     */
    servicePort: string;
}

export function IoK8sApiExtensionsV1beta1IngressBackendFromJSON(json: any): IoK8sApiExtensionsV1beta1IngressBackend {
    return {
        'serviceName': json['serviceName'],
        'servicePort': json['servicePort'],
    };
}

export function IoK8sApiExtensionsV1beta1IngressBackendToJSON(value?: IoK8sApiExtensionsV1beta1IngressBackend): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'serviceName': value.serviceName,
        'servicePort': value.servicePort,
    };
}


