// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiCoreV1PersistentVolumeSpec,
    IoK8sApiCoreV1PersistentVolumeSpecFromJSON,
    IoK8sApiCoreV1PersistentVolumeSpecToJSON,
    IoK8sApiCoreV1PersistentVolumeStatus,
    IoK8sApiCoreV1PersistentVolumeStatusFromJSON,
    IoK8sApiCoreV1PersistentVolumeStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * PersistentVolume (PV) is a storage resource provisioned by an administrator. It is analogous to a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes
 * @export
 * @interface IoK8sApiCoreV1PersistentVolume
 */
export interface IoK8sApiCoreV1PersistentVolume {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiCoreV1PersistentVolume
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiCoreV1PersistentVolume
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiCoreV1PersistentVolume
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiCoreV1PersistentVolumeSpec}
     * @memberof IoK8sApiCoreV1PersistentVolume
     */
    spec?: IoK8sApiCoreV1PersistentVolumeSpec;
    /**
     * 
     * @type {IoK8sApiCoreV1PersistentVolumeStatus}
     * @memberof IoK8sApiCoreV1PersistentVolume
     */
    status?: IoK8sApiCoreV1PersistentVolumeStatus;
}

export function IoK8sApiCoreV1PersistentVolumeFromJSON(json: any): IoK8sApiCoreV1PersistentVolume {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : IoK8sApiCoreV1PersistentVolumeSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiCoreV1PersistentVolumeStatusFromJSON(json['status']),
    };
}

export function IoK8sApiCoreV1PersistentVolumeToJSON(value?: IoK8sApiCoreV1PersistentVolume): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiCoreV1PersistentVolumeSpecToJSON(value.spec),
        'status': IoK8sApiCoreV1PersistentVolumeStatusToJSON(value.status),
    };
}


