// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1NodeSelectorTerm,
    IoK8sApiCoreV1NodeSelectorTermFromJSON,
    IoK8sApiCoreV1NodeSelectorTermToJSON,
} from './';

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 * @export
 * @interface IoK8sApiCoreV1NodeSelector
 */
export interface IoK8sApiCoreV1NodeSelector {
    /**
     * Required. A list of node selector terms. The terms are ORed.
     * @type {Array<IoK8sApiCoreV1NodeSelectorTerm>}
     * @memberof IoK8sApiCoreV1NodeSelector
     */
    nodeSelectorTerms: Array<IoK8sApiCoreV1NodeSelectorTerm>;
}

export function IoK8sApiCoreV1NodeSelectorFromJSON(json: any): IoK8sApiCoreV1NodeSelector {
    return {
        'nodeSelectorTerms': (json['nodeSelectorTerms'] as Array<any>).map(IoK8sApiCoreV1NodeSelectorTermFromJSON),
    };
}

export function IoK8sApiCoreV1NodeSelectorToJSON(value?: IoK8sApiCoreV1NodeSelector): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'nodeSelectorTerms': (value.nodeSelectorTerms as Array<any>).map(IoK8sApiCoreV1NodeSelectorTermToJSON),
    };
}


