// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReference,
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceFromJSON,
    IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceToJSON,
    IoK8sApiAutoscalingV2beta2MetricIdentifier,
    IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON,
    IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON,
    IoK8sApiAutoscalingV2beta2MetricTarget,
    IoK8sApiAutoscalingV2beta2MetricTargetFromJSON,
    IoK8sApiAutoscalingV2beta2MetricTargetToJSON,
} from './index.ts';

/**
 * ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ObjectMetricSource
 */
export interface IoK8sApiAutoscalingV2beta2ObjectMetricSource {
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2CrossVersionObjectReference}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2MetricTarget}
     * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricSource
     */
    target: IoK8sApiAutoscalingV2beta2MetricTarget;
}

export function IoK8sApiAutoscalingV2beta2ObjectMetricSourceFromJSON(json: any): IoK8sApiAutoscalingV2beta2ObjectMetricSource {
    return {
        'describedObject': IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceFromJSON(json['describedObject']),
        'metric': IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON(json['metric']),
        'target': IoK8sApiAutoscalingV2beta2MetricTargetFromJSON(json['target']),
    };
}

export function IoK8sApiAutoscalingV2beta2ObjectMetricSourceToJSON(value?: IoK8sApiAutoscalingV2beta2ObjectMetricSource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'describedObject': IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceToJSON(value.describedObject),
        'metric': IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON(value.metric),
        'target': IoK8sApiAutoscalingV2beta2MetricTargetToJSON(value.target),
    };
}


