// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet,
    IoK8sApiExtensionsV1beta1RollingUpdateDaemonSetFromJSON,
    IoK8sApiExtensionsV1beta1RollingUpdateDaemonSetToJSON,
} from './';

/**
 * 
 * @export
 * @interface IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
 */
export interface IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy {
    /**
     * 
     * @type {IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet}
     * @memberof IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
     */
    rollingUpdate?: IoK8sApiExtensionsV1beta1RollingUpdateDaemonSet;
    /**
     * Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is OnDelete.
     * @type {string}
     * @memberof IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy
     */
    type?: string;
}

export function IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategyFromJSON(json: any): IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy {
    return {
        'rollingUpdate': !exists(json, 'rollingUpdate') ? undefined : IoK8sApiExtensionsV1beta1RollingUpdateDaemonSetFromJSON(json['rollingUpdate']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategyToJSON(value?: IoK8sApiExtensionsV1beta1DaemonSetUpdateStrategy): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'rollingUpdate': IoK8sApiExtensionsV1beta1RollingUpdateDaemonSetToJSON(value.rollingUpdate),
        'type': value.type,
    };
}


