// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiExtensionsV1beta1NetworkPolicyPeer,
    IoK8sApiExtensionsV1beta1NetworkPolicyPeerFromJSON,
    IoK8sApiExtensionsV1beta1NetworkPolicyPeerToJSON,
    IoK8sApiExtensionsV1beta1NetworkPolicyPort,
    IoK8sApiExtensionsV1beta1NetworkPolicyPortFromJSON,
    IoK8sApiExtensionsV1beta1NetworkPolicyPortToJSON,
} from './index.ts';

/**
 * DEPRECATED 1.9 - This group version of NetworkPolicyEgressRule is deprecated by networking/v1/NetworkPolicyEgressRule. NetworkPolicyEgressRule describes a particular set of traffic that is allowed out of pods matched by a NetworkPolicySpec\'s podSelector. The traffic must match both ports and to. This type is beta-level in 1.8
 * @export
 * @interface IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule
 */
export interface IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule {
    /**
     * List of destination ports for outgoing traffic. Each item in this list is combined using a logical OR. If this field is empty or missing, this rule matches all ports (traffic not restricted by port). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
     * @type {Array<IoK8sApiExtensionsV1beta1NetworkPolicyPort>}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule
     */
    ports?: Array<IoK8sApiExtensionsV1beta1NetworkPolicyPort>;
    /**
     * List of destinations for outgoing traffic of pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is empty or missing, this rule matches all destinations (traffic not restricted by destination). If this field is present and contains at least one item, this rule allows traffic only if the traffic matches at least one item in the to list.
     * @type {Array<IoK8sApiExtensionsV1beta1NetworkPolicyPeer>}
     * @memberof IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule
     */
    to?: Array<IoK8sApiExtensionsV1beta1NetworkPolicyPeer>;
}

export function IoK8sApiExtensionsV1beta1NetworkPolicyEgressRuleFromJSON(json: any): IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule {
    return {
        'ports': !exists(json, 'ports') ? undefined : (json['ports'] as Array<any>).map(IoK8sApiExtensionsV1beta1NetworkPolicyPortFromJSON),
        'to': !exists(json, 'to') ? undefined : (json['to'] as Array<any>).map(IoK8sApiExtensionsV1beta1NetworkPolicyPeerFromJSON),
    };
}

export function IoK8sApiExtensionsV1beta1NetworkPolicyEgressRuleToJSON(value?: IoK8sApiExtensionsV1beta1NetworkPolicyEgressRule): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'ports': value.ports === undefined ? undefined : (value.ports as Array<any>).map(IoK8sApiExtensionsV1beta1NetworkPolicyPortToJSON),
        'to': value.to === undefined ? undefined : (value.to as Array<any>).map(IoK8sApiExtensionsV1beta1NetworkPolicyPeerToJSON),
    };
}


