// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ScaleSpec describes the attributes of a scale subresource
 * @export
 * @interface IoK8sApiAppsV1beta2ScaleSpec
 */
export interface IoK8sApiAppsV1beta2ScaleSpec {
    /**
     * desired number of instances for the scaled object.
     * @type {number}
     * @memberof IoK8sApiAppsV1beta2ScaleSpec
     */
    replicas?: number;
}

export function IoK8sApiAppsV1beta2ScaleSpecFromJSON(json: any): IoK8sApiAppsV1beta2ScaleSpec {
    return {
        'replicas': !exists(json, 'replicas') ? undefined : json['replicas'],
    };
}

export function IoK8sApiAppsV1beta2ScaleSpecToJSON(value?: IoK8sApiAppsV1beta2ScaleSpec): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'replicas': value.replicas,
    };
}


