// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiCoreV1LoadBalancerIngress,
    IoK8sApiCoreV1LoadBalancerIngressFromJSON,
    IoK8sApiCoreV1LoadBalancerIngressToJSON,
} from './index.ts';

/**
 * LoadBalancerStatus represents the status of a load-balancer.
 * @export
 * @interface IoK8sApiCoreV1LoadBalancerStatus
 */
export interface IoK8sApiCoreV1LoadBalancerStatus {
    /**
     * Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
     * @type {Array<IoK8sApiCoreV1LoadBalancerIngress>}
     * @memberof IoK8sApiCoreV1LoadBalancerStatus
     */
    ingress?: Array<IoK8sApiCoreV1LoadBalancerIngress>;
}

export function IoK8sApiCoreV1LoadBalancerStatusFromJSON(json: any): IoK8sApiCoreV1LoadBalancerStatus {
    return {
        'ingress': !exists(json, 'ingress') ? undefined : (json['ingress'] as Array<any>).map(IoK8sApiCoreV1LoadBalancerIngressFromJSON),
    };
}

export function IoK8sApiCoreV1LoadBalancerStatusToJSON(value?: IoK8sApiCoreV1LoadBalancerStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'ingress': value.ingress === undefined ? undefined : (value.ingress as Array<any>).map(IoK8sApiCoreV1LoadBalancerIngressToJSON),
    };
}


