// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAppsV1beta2ReplicaSetSpec,
    IoK8sApiAppsV1beta2ReplicaSetSpecFromJSON,
    IoK8sApiAppsV1beta2ReplicaSetSpecToJSON,
    IoK8sApiAppsV1beta2ReplicaSetStatus,
    IoK8sApiAppsV1beta2ReplicaSetStatusFromJSON,
    IoK8sApiAppsV1beta2ReplicaSetStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * DEPRECATED - This group version of ReplicaSet is deprecated by apps/v1/ReplicaSet. See the release notes for more information. ReplicaSet ensures that a specified number of pod replicas are running at any given time.
 * @export
 * @interface IoK8sApiAppsV1beta2ReplicaSet
 */
export interface IoK8sApiAppsV1beta2ReplicaSet {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2ReplicaSetSpec}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    spec?: IoK8sApiAppsV1beta2ReplicaSetSpec;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2ReplicaSetStatus}
     * @memberof IoK8sApiAppsV1beta2ReplicaSet
     */
    status?: IoK8sApiAppsV1beta2ReplicaSetStatus;
}

export function IoK8sApiAppsV1beta2ReplicaSetFromJSON(json: any): IoK8sApiAppsV1beta2ReplicaSet {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : IoK8sApiAppsV1beta2ReplicaSetSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiAppsV1beta2ReplicaSetStatusFromJSON(json['status']),
    };
}

export function IoK8sApiAppsV1beta2ReplicaSetToJSON(value?: IoK8sApiAppsV1beta2ReplicaSet): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiAppsV1beta2ReplicaSetSpecToJSON(value.spec),
        'status': IoK8sApiAppsV1beta2ReplicaSetStatusToJSON(value.status),
    };
}


