// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAppsV1beta2DeploymentSpec,
    IoK8sApiAppsV1beta2DeploymentSpecFromJSON,
    IoK8sApiAppsV1beta2DeploymentSpecToJSON,
    IoK8sApiAppsV1beta2DeploymentStatus,
    IoK8sApiAppsV1beta2DeploymentStatusFromJSON,
    IoK8sApiAppsV1beta2DeploymentStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * DEPRECATED - This group version of Deployment is deprecated by apps/v1/Deployment. See the release notes for more information. Deployment enables declarative updates for Pods and ReplicaSets.
 * @export
 * @interface IoK8sApiAppsV1beta2Deployment
 */
export interface IoK8sApiAppsV1beta2Deployment {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2Deployment
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAppsV1beta2Deployment
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAppsV1beta2Deployment
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2DeploymentSpec}
     * @memberof IoK8sApiAppsV1beta2Deployment
     */
    spec?: IoK8sApiAppsV1beta2DeploymentSpec;
    /**
     * 
     * @type {IoK8sApiAppsV1beta2DeploymentStatus}
     * @memberof IoK8sApiAppsV1beta2Deployment
     */
    status?: IoK8sApiAppsV1beta2DeploymentStatus;
}

export function IoK8sApiAppsV1beta2DeploymentFromJSON(json: any): IoK8sApiAppsV1beta2Deployment {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : IoK8sApiAppsV1beta2DeploymentSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiAppsV1beta2DeploymentStatusFromJSON(json['status']),
    };
}

export function IoK8sApiAppsV1beta2DeploymentToJSON(value?: IoK8sApiAppsV1beta2Deployment): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiAppsV1beta2DeploymentSpecToJSON(value.spec),
        'status': IoK8sApiAppsV1beta2DeploymentStatusToJSON(value.status),
    };
}


