// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiNetworkingV1beta1IngressSpec,
    IoK8sApiNetworkingV1beta1IngressSpecFromJSON,
    IoK8sApiNetworkingV1beta1IngressSpecToJSON,
    IoK8sApiNetworkingV1beta1IngressStatus,
    IoK8sApiNetworkingV1beta1IngressStatusFromJSON,
    IoK8sApiNetworkingV1beta1IngressStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * Ingress is a collection of rules that allow inbound connections to reach the endpoints defined by a backend. An Ingress can be configured to give services externally-reachable urls, load balance traffic, terminate SSL, offer name based virtual hosting etc.
 * @export
 * @interface IoK8sApiNetworkingV1beta1Ingress
 */
export interface IoK8sApiNetworkingV1beta1Ingress {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiNetworkingV1beta1Ingress
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiNetworkingV1beta1Ingress
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiNetworkingV1beta1Ingress
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiNetworkingV1beta1IngressSpec}
     * @memberof IoK8sApiNetworkingV1beta1Ingress
     */
    spec?: IoK8sApiNetworkingV1beta1IngressSpec;
    /**
     * 
     * @type {IoK8sApiNetworkingV1beta1IngressStatus}
     * @memberof IoK8sApiNetworkingV1beta1Ingress
     */
    status?: IoK8sApiNetworkingV1beta1IngressStatus;
}

export function IoK8sApiNetworkingV1beta1IngressFromJSON(json: any): IoK8sApiNetworkingV1beta1Ingress {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': !exists(json, 'spec') ? undefined : IoK8sApiNetworkingV1beta1IngressSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiNetworkingV1beta1IngressStatusFromJSON(json['status']),
    };
}

export function IoK8sApiNetworkingV1beta1IngressToJSON(value?: IoK8sApiNetworkingV1beta1Ingress): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiNetworkingV1beta1IngressSpecToJSON(value.spec),
        'status': IoK8sApiNetworkingV1beta1IngressStatusToJSON(value.status),
    };
}


