// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 * CrossVersionObjectReference contains enough information to let you identify the referred resource.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
 */
export interface IoK8sApiAutoscalingV2beta2CrossVersionObjectReference {
    /**
     * API version of the referent
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    apiVersion?: string;
    /**
     * Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds\"
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    kind: string;
    /**
     * Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2CrossVersionObjectReference
     */
    name: string;
}

export function IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceFromJSON(json: any): IoK8sApiAutoscalingV2beta2CrossVersionObjectReference {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': json['kind'],
        'name': json['name'],
    };
}

export function IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceToJSON(value?: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'name': value.name,
    };
}


