// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1NodeSelectorTerm,
    IoK8sApiCoreV1NodeSelectorTermFromJSON,
    IoK8sApiCoreV1NodeSelectorTermToJSON,
} from './';

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it\'s a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 * @export
 * @interface IoK8sApiCoreV1PreferredSchedulingTerm
 */
export interface IoK8sApiCoreV1PreferredSchedulingTerm {
    /**
     * 
     * @type {IoK8sApiCoreV1NodeSelectorTerm}
     * @memberof IoK8sApiCoreV1PreferredSchedulingTerm
     */
    preference: IoK8sApiCoreV1NodeSelectorTerm;
    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     * @type {number}
     * @memberof IoK8sApiCoreV1PreferredSchedulingTerm
     */
    weight: number;
}

export function IoK8sApiCoreV1PreferredSchedulingTermFromJSON(json: any): IoK8sApiCoreV1PreferredSchedulingTerm {
    return {
        'preference': IoK8sApiCoreV1NodeSelectorTermFromJSON(json['preference']),
        'weight': json['weight'],
    };
}

export function IoK8sApiCoreV1PreferredSchedulingTermToJSON(value?: IoK8sApiCoreV1PreferredSchedulingTerm): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'preference': IoK8sApiCoreV1NodeSelectorTermToJSON(value.preference),
        'weight': value.weight,
    };
}


