// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiCoreV1LoadBalancerStatus,
    IoK8sApiCoreV1LoadBalancerStatusFromJSON,
    IoK8sApiCoreV1LoadBalancerStatusToJSON,
} from './index.ts';

/**
 * IngressStatus describe the current state of the Ingress.
 * @export
 * @interface IoK8sApiExtensionsV1beta1IngressStatus
 */
export interface IoK8sApiExtensionsV1beta1IngressStatus {
    /**
     * 
     * @type {IoK8sApiCoreV1LoadBalancerStatus}
     * @memberof IoK8sApiExtensionsV1beta1IngressStatus
     */
    loadBalancer?: IoK8sApiCoreV1LoadBalancerStatus;
}

export function IoK8sApiExtensionsV1beta1IngressStatusFromJSON(json: any): IoK8sApiExtensionsV1beta1IngressStatus {
    return {
        'loadBalancer': !exists(json, 'loadBalancer') ? undefined : IoK8sApiCoreV1LoadBalancerStatusFromJSON(json['loadBalancer']),
    };
}

export function IoK8sApiExtensionsV1beta1IngressStatusToJSON(value?: IoK8sApiExtensionsV1beta1IngressStatus): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'loadBalancer': IoK8sApiCoreV1LoadBalancerStatusToJSON(value.loadBalancer),
    };
}


