// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ContainerStateRunning is a running state of a container.
 * @export
 * @interface IoK8sApiCoreV1ContainerStateRunning
 */
export interface IoK8sApiCoreV1ContainerStateRunning {
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     * @type {Date}
     * @memberof IoK8sApiCoreV1ContainerStateRunning
     */
    startedAt?: Date;
}

export function IoK8sApiCoreV1ContainerStateRunningFromJSON(json: any): IoK8sApiCoreV1ContainerStateRunning {
    return {
        'startedAt': !exists(json, 'startedAt') ? undefined : new Date(json['startedAt']),
    };
}

export function IoK8sApiCoreV1ContainerStateRunningToJSON(value?: IoK8sApiCoreV1ContainerStateRunning): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'startedAt': value.startedAt === undefined ? undefined : value.startedAt.toISOString(),
    };
}


