// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiAutoscalingV2beta2MetricTarget,
    IoK8sApiAutoscalingV2beta2MetricTargetFromJSON,
    IoK8sApiAutoscalingV2beta2MetricTargetToJSON,
} from './';

/**
 * ResourceMetricSource indicates how to scale on a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  The values will be averaged together before being compared to the target.  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.  Only one \"target\" type should be set.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ResourceMetricSource
 */
export interface IoK8sApiAutoscalingV2beta2ResourceMetricSource {
    /**
     * name is the name of the resource in question.
     * @type {string}
     * @memberof IoK8sApiAutoscalingV2beta2ResourceMetricSource
     */
    name: string;
    /**
     * 
     * @type {IoK8sApiAutoscalingV2beta2MetricTarget}
     * @memberof IoK8sApiAutoscalingV2beta2ResourceMetricSource
     */
    target: IoK8sApiAutoscalingV2beta2MetricTarget;
}

export function IoK8sApiAutoscalingV2beta2ResourceMetricSourceFromJSON(json: any): IoK8sApiAutoscalingV2beta2ResourceMetricSource {
    return {
        'name': json['name'],
        'target': IoK8sApiAutoscalingV2beta2MetricTargetFromJSON(json['target']),
    };
}

export function IoK8sApiAutoscalingV2beta2ResourceMetricSourceToJSON(value?: IoK8sApiAutoscalingV2beta2ResourceMetricSource): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'target': IoK8sApiAutoscalingV2beta2MetricTargetToJSON(value.target),
    };
}


