// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * DaemonEndpoint contains information about a single Daemon endpoint.
 * @export
 * @interface IoK8sApiCoreV1DaemonEndpoint
 */
export interface IoK8sApiCoreV1DaemonEndpoint {
    /**
     * Port number of the given endpoint.
     * @type {number}
     * @memberof IoK8sApiCoreV1DaemonEndpoint
     */
    port: number;
}

export function IoK8sApiCoreV1DaemonEndpointFromJSON(json: any): IoK8sApiCoreV1DaemonEndpoint {
    return {
        'port': json['Port'],
    };
}

export function IoK8sApiCoreV1DaemonEndpointToJSON(value?: IoK8sApiCoreV1DaemonEndpoint): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'Port': value.port,
    };
}


