// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiCoreV1ClientIPConfig,
    IoK8sApiCoreV1ClientIPConfigFromJSON,
    IoK8sApiCoreV1ClientIPConfigToJSON,
} from './index.ts';

/**
 * SessionAffinityConfig represents the configurations of session affinity.
 * @export
 * @interface IoK8sApiCoreV1SessionAffinityConfig
 */
export interface IoK8sApiCoreV1SessionAffinityConfig {
    /**
     * 
     * @type {IoK8sApiCoreV1ClientIPConfig}
     * @memberof IoK8sApiCoreV1SessionAffinityConfig
     */
    clientIP?: IoK8sApiCoreV1ClientIPConfig;
}

export function IoK8sApiCoreV1SessionAffinityConfigFromJSON(json: any): IoK8sApiCoreV1SessionAffinityConfig {
    return {
        'clientIP': !exists(json, 'clientIP') ? undefined : IoK8sApiCoreV1ClientIPConfigFromJSON(json['clientIP']),
    };
}

export function IoK8sApiCoreV1SessionAffinityConfigToJSON(value?: IoK8sApiCoreV1SessionAffinityConfig): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'clientIP': IoK8sApiCoreV1ClientIPConfigToJSON(value.clientIP),
    };
}


