// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
import {
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpecFromJSON,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpecToJSON,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatusFromJSON,
    IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatusToJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMeta,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
    IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './index.ts';

/**
 * LocalSubjectAccessReview checks whether or not a user or group can perform an action in a given namespace. Having a namespace scoped resource makes it much easier to grant namespace scoped policy that includes permissions checking.
 * @export
 * @interface IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
 */
export interface IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
     * @type {string}
     * @memberof IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
     * @type {string}
     * @memberof IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
     */
    kind?: string;
    /**
     * 
     * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
     */
    metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec}
     * @memberof IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
     */
    spec: IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpec;
    /**
     * 
     * @type {IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus}
     * @memberof IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview
     */
    status?: IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatus;
}

export function IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewFromJSON(json: any): IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview {
    return {
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': !exists(json, 'metadata') ? undefined : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
        'spec': IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpecFromJSON(json['spec']),
        'status': !exists(json, 'status') ? undefined : IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatusFromJSON(json['status']),
    };
}

export function IoK8sApiAuthorizationV1beta1LocalSubjectAccessReviewToJSON(value?: IoK8sApiAuthorizationV1beta1LocalSubjectAccessReview): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
        'spec': IoK8sApiAuthorizationV1beta1SubjectAccessReviewSpecToJSON(value.spec),
        'status': IoK8sApiAuthorizationV1beta1SubjectAccessReviewStatusToJSON(value.status),
    };
}


