// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1Handler,
    IoK8sApiCoreV1HandlerFromJSON,
    IoK8sApiCoreV1HandlerToJSON,
} from './';

/**
 * Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
 * @export
 * @interface IoK8sApiCoreV1Lifecycle
 */
export interface IoK8sApiCoreV1Lifecycle {
    /**
     * 
     * @type {IoK8sApiCoreV1Handler}
     * @memberof IoK8sApiCoreV1Lifecycle
     */
    postStart?: IoK8sApiCoreV1Handler;
    /**
     * 
     * @type {IoK8sApiCoreV1Handler}
     * @memberof IoK8sApiCoreV1Lifecycle
     */
    preStop?: IoK8sApiCoreV1Handler;
}

export function IoK8sApiCoreV1LifecycleFromJSON(json: any): IoK8sApiCoreV1Lifecycle {
    return {
        'postStart': !exists(json, 'postStart') ? undefined : IoK8sApiCoreV1HandlerFromJSON(json['postStart']),
        'preStop': !exists(json, 'preStop') ? undefined : IoK8sApiCoreV1HandlerFromJSON(json['preStop']),
    };
}

export function IoK8sApiCoreV1LifecycleToJSON(value?: IoK8sApiCoreV1Lifecycle): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'postStart': IoK8sApiCoreV1HandlerToJSON(value.postStart),
        'preStop': IoK8sApiCoreV1HandlerToJSON(value.preStop),
    };
}


