// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1LimitRangeItem,
    IoK8sApiCoreV1LimitRangeItemFromJSON,
    IoK8sApiCoreV1LimitRangeItemToJSON,
} from './';

/**
 * LimitRangeSpec defines a min/max usage limit for resources that match on kind.
 * @export
 * @interface IoK8sApiCoreV1LimitRangeSpec
 */
export interface IoK8sApiCoreV1LimitRangeSpec {
    /**
     * Limits is the list of LimitRangeItem objects that are enforced.
     * @type {Array<IoK8sApiCoreV1LimitRangeItem>}
     * @memberof IoK8sApiCoreV1LimitRangeSpec
     */
    limits: Array<IoK8sApiCoreV1LimitRangeItem>;
}

export function IoK8sApiCoreV1LimitRangeSpecFromJSON(json: any): IoK8sApiCoreV1LimitRangeSpec {
    return {
        'limits': (json['limits'] as Array<any>).map(IoK8sApiCoreV1LimitRangeItemFromJSON),
    };
}

export function IoK8sApiCoreV1LimitRangeSpecToJSON(value?: IoK8sApiCoreV1LimitRangeSpec): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'limits': (value.limits as Array<any>).map(IoK8sApiCoreV1LimitRangeItemToJSON),
    };
}


