// tslint:disable
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace
 * @export
 * @interface IoK8sApiCoreV1SecretReference
 */
export interface IoK8sApiCoreV1SecretReference {
    /**
     * Name is unique within a namespace to reference a secret resource.
     * @type {string}
     * @memberof IoK8sApiCoreV1SecretReference
     */
    name?: string;
    /**
     * Namespace defines the space within which the secret name must be unique.
     * @type {string}
     * @memberof IoK8sApiCoreV1SecretReference
     */
    namespace?: string;
}

export function IoK8sApiCoreV1SecretReferenceFromJSON(json: any): IoK8sApiCoreV1SecretReference {
    return {
        'name': !exists(json, 'name') ? undefined : json['name'],
        'namespace': !exists(json, 'namespace') ? undefined : json['namespace'],
    };
}

export function IoK8sApiCoreV1SecretReferenceToJSON(value?: IoK8sApiCoreV1SecretReference): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'namespace': value.namespace,
    };
}


